python=/nfs/volume-100003-1/raochongzhi/envs/tf_a6000/bin/python
hadoop="/usr/local/hadoop-current/bin/hadoop"
hadoop_jar=/usr/local/hadoop-current/share/hadoop/tools/lib/hadoop-streaming-2.7.2-1906.jar
hadoopstreaming="${hadoop} jar ${hadoop_jar} -D stream.non.zero.exit.is.failure=false"
hadoop_queue="root.soda_i18n_trading_stg_prod"
hdfs_prefix="hdfs://DClusterUS1"

#fea path
hadoop_fea_root=/user/prod_soda_trade_strategy/rank/jiazhuo/hash_fea_new/train/
train_hdfs_dir="${hdfs_prefix}${hadoop_fea_root}"

#get current dir,to override manually, just set: proj_name=xxx
proj_name=$(basename "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")

#model path
hadoop_root=/user/prod_soda_trade_strategy/rank/chenpinyuan/train_model_nb_br/${proj_name}/
hadoop_serving_model=$hadoop_root"/serving_model"

is_auto_train=0
need_test=1
need_dump_serving_model=1

train_start_day=20260303
train_end_day=20260720
test_start_day=20260721
test_end_day=20260724

#submit luban user and path
USER_UUID="fb8b6210117a4930b598581b5a1da5fa"
JOB_NAME="${proj_name}_train"
SCRIPT_PATH="/nfs/dataset-ofs-rank-ssl/chenpinyuan/tf_rank_BR/${proj_name}/train.sh"
RESOURCE_UUID="8d053ced94df4883837eb91a1afa9a87"
PRIORITY=1
